WITH HOURS AS (
    SELECT num AS HOUR 
    FROM numbers 
    WHERE num BETWEEN 0 AND 23
),
HOUR_COUNT AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)
SELECT H.HOUR, IFNULL(C.COUNT, 0) AS COUNT
FROM HOURS H
LEFT JOIN HOUR_COUNT C ON H.HOUR = C.HOUR
ORDER BY H.HOUR;

#ㅋㅋ ㅈㅅ