SELECT YEAR(ORI.DIFFERENTIATION_DATE) AS YEAR, (NEW.BIG-ORI.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA AS ORI
LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS MYEAR, MAX(SIZE_OF_COLONY) AS BIG
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)AS NEW ON YEAR(ORI.DIFFERENTIATION_DATE) = NEW.MYEAR
ORDER BY YEAR, YEAR_DEV;