SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SUM(SALES * PRICE)) AS TOTAL_SALES
FROM BOOK
JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
) AS SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY BOOK.AUTHOR_ID, CATEGORY
ORDER BY BOOK.AUTHOR_ID, CATEGORY DESC