SELECT EMP.EMP_NO, EMP_NAME, 
        CASE
            WHEN SCORE >= 96 THEN 'S'
            WHEN SCORE >= 90 THEN 'A'
            WHEN SCORE >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE,
        CASE
            WHEN SCORE >= 96 THEN SAL*0.2
            WHEN SCORE >= 90 THEN SAL*0.15
            WHEN SCORE >= 80 THEN SAL*0.1
            ELSE 0
        END AS BONUS
FROM HR_EMPLOYEES AS EMP
# JOIN HR_DEPARTMENT AS DEP ON EMP.DEPT_ID = DEP.DEPT_ID
# 이 테이블 왜 줌?
JOIN (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ) AS GR ON EMP.EMP_NO = GR.EMP_NO
ORDER BY EMP.EMP_NO