SELECT HISTORY_ID, ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE) + 1)*(100-IFNULL(DISCOUNT_RATE,0))/100,0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON HIS.CAR_ID = CAR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DIS ON CAR.CAR_TYPE = DIS.CAR_TYPE
    AND DURATION_TYPE =
        CASE 
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
        END
WHERE CAR.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;